name: 테라폼을 활용하여 AWS 인프라 배포/삭제


#깃헙 UI 설정
on: 
  workflow_dispatch:       #깃헙 UI에서 버튼을 눌러 작업이 Run 되게 만듬
    inputs:
      actions_type:      #깃헙 UI에서 배포할지 삭제할지 고르는 버튼을 만듬
        description: "원하는 작업을 선택하세요 (apply 또는 destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

#러너vm 생성
jobs: 
  terraform_job:
    runs-on: ubuntu-latest      


#공통작업
    steps:
    - name: 1. 테라폼 코드를 러너 내부로 다운로드 # 내부 디폴트 경로는, /home/runner/work/terraform-project/terraform-project/ )
      uses: actions/checkout@v4      

    - name: 2. AWS 계정 연결  #깃헙 secret은 미리 등록해둠 
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_STEPHANE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STEPHANE }}
        aws-region: ap-northeast-2
      
    - name: 3. 테라폼 툴 설치
      uses: hashicorp/setup-terraform@v3

    - name: 4. terraform init     # 초기화는 배포,삭제 모두 필수
      run: terraform init



#테라폼 배포 (apply 버튼 누를 시)
    - name: 1. terraform plan
      if: ${{ github.event.inputs.actions_type == 'apply' }}
      run: terraform plan -out=apply_plan

    - name: 2. terraform apply
      if: ${{ github.event.inputs.actions_type == 'apply' }}
      run: terraform apply --auto-approve apply_plan




#테라폼 삭제 (destroy 버튼 누를 시)
    - name: 1. terraform plan
      if: ${{ github.event.inputs.actions_type == 'destroy' }}
      run: terraform plan -destroy -out=destroy_plan

    - name: 2. terraform destroy
      if: ${{ github.event.inputs.actions_type == 'destroy' }}
      run: terraform apply --auto-approve destroy_plan
