name: "Terraform & Ansible IaC"

on: 
  workflow_dispatch     #github UI에서 수동으로 Run 버튼 눌러야 배포


jobs:

#ubuntu VM 생성
  deploy:
    runs-on: ubuntu-latest


### 공통 준비 작업 ###
    steps: 
    - name: 1. 테라폼 코드를 러너로 다운로드
      uses: actions/checkout@v4
      with: 
        path: "terraform-project"     #러너 내부의 경로로 해당 폴더에 테라폼 코드를 다운로드 하겠다라는 의미

    - name: 2. 앤서블 코드를 러너로 다운로드
      uses: actions/checkout@v4
      with:
        repository: "rlfrjs3/ansible-project"
        token: ${{ secrets.ANSIBLE_REPO_TOKEN }}
        path: "ansible-project"

    - name: 3. AWS 계정 인증
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_STEPHANE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STEPHANE }}
        aws-region: ap-northeast-2


### 테라폼 관련 작업 ###
    - name: 1. Setup Terraform
      uses: hashicorp/setup-terraform@v3
 
    - name: 2. Terraform Init
      working-directory: ./terraform-project
      run: terraform init
  
    - name: 3. Terraform Plan
      working-directory: ./terraform-project
      run: terraform plan -out=plan_output

    - name: 4. Terraform Apply
      working-directory: ./terraform-project
      run: terraform apply --auto-approve plan_output


### 앤서블 관련 작업 ###
#    - name: 1. BASTION_IP 추출 및 환경변수 저장
#      working-directory: ./ansible-project
#      run: |   
#        BASTION_IP=$(terraform output -raw bastionhost_public_ip)
#        echo "BASTION_IP=$BASTION_IP" >> $GITHUB_ENV
#
#    - name: 2. 앤서블용 파이썬 라이브러리 설치 (추가)
#      working-directory: ./ansible-project
#      run: | 
#        python3 -m pip install boto3 botocore
#
#    - name: 3. EC2 SSH 접속을 위한 비밀키 러너 내부 파일로 생성
#      working-directory: ./ansible-project
#      run: |  
#        echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > ansible-project/iac_keypair.pem
#        chmod 600 ansible-project/iac_keypair.pem
#
#    - name: 4. ansible_ci.cfg에 배스천호스트의 공인ip 주입
#      working-directory: ./ansible-project 
#      run: |
#        sed -i "s/BASTION_IP_PLACEHOLDER/${{ env.BASTION_IP }}/g" ansible_ci.cfg
#
#    - name: 5. 플레이북 실행 
#      working-directory: ./ansible-project
#      run: | 
#        export ANSIBLE_CONFIG="./ansible_ci.cfg"
#        ansible-playbook playbook/first_setting.yml

