name: 테라폼을 사용한 AWS 인프라 배포 (init -> plan -> apply)


#언제 작동할 것인가? -> 깃헙 사이트에서 [배포 버튼]을 누르면
on:
  workflow_dispatch:


jobs: 
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. 깃헙 저장소에서 코드를 러너VM에  가져오기 (Checkout)
      uses: actions/checkout@v4

    - name: 2. AWS profile 인증 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_STEPHANE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STEPHANE }}
        aws-region: ap-northeast-2

    - name: 3. 러너VM에 테라폼 설치
      uses: hashicorp/setup-terraform@v3

    - name: 4. 테라폼 초기화 (init)
      run: | 
        terraform init
 
    - name: 5. 테라폼 배포 계획 확인 (plan)
      run: | 
        terraform plan
 
    - name: 6. 테라폼 실제 배포 (apply)
      run: | 
        terraform apply -auto-approve



